apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service
spec:
  template:
    spec:
      containers:
      - name: go-service
        image: habib0905/urlshortener-go-service:10686cae180f831cb3a73c7a23df0af029bb5897
